### PR TITLE
Introduce relation type rename

### LINKED ISSUE #511: Introduce refactoring to rename relationship types

### PR DESCRIPTION
**Pull request by fbiville**
Fixes #511

### CODE REVIEW

**Comment by fbiville** [comment]
TODO: docs

**Review by filipelautert — COMMENTED** [review]
Don't you need a xsd entry for rename type?

**Comment by fbiville** [comment]
> Don't you need a xsd entry for rename type?

Oops, totally forgot to do that 😅. Thanks for the reminder!

**Review by filipelautert — APPROVED** [review]
Code wise looks good!

**Pull request merged**
