### PR TITLE
JReleaser configuration updates

### PR DESCRIPTION
**Pull request by aalmiray**
- adds JARs as release assets (#216)
- configures conventional-commits as changelog preset

### CODE REVIEW

**Comment by fbiville** [comment]
Thanks for the update @aalmiray!
When I locally run:
```shell
mvn jreleaser:release -Prelease -Dversion.to.release=4.15.0.1
```
I get the following error:
```
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.1.0:release (default-cli) on project liquibase-neo4j: Unable to parse configuration of mojo org.jreleaser:jreleaser-maven-plugin:1.1.0:release for parameter preset: Cannot find 'preset' in class org.jreleaser.maven.plugin.Github -> [Help 1]
```

**Comment by aalmiray** [comment]
Oops, `<preset>` should be inside `<changelog>`. Let me fix it quickly

**Comment by fbiville** [comment]
Thanks, it goes a bit further:
```shell
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.1.0:release (default-cli) on project liquibase-neo4j: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.1.0:release failed: Path does not exist target/liquibase-neo4j-4.15.0.2-SNAPSHOT.jar -> [Help 1]
```

The problem is I don't want JReleaser to upload files but rather keep the ones that are already uploaded to the GitHub release. Is there a way to achieve this?

**Comment by aalmiray** [comment]
Oh? So you manually upload the files to the Git release? Which I'd assume is created by other means and not by JReleaser.
Well, if that's the case then remove the `files` section, also remove `<release>github><overwrite>` and set `<release><github><update><enabled>` && `<release><github><update><sections><section>BODY` as I'd assume you only want to update the release with the changelog, amirite?

**Comment by fbiville** [comment]
@aalmiray another tool uploads the files. Thanks, I'll try your suggestions!

**Comment by fbiville** [comment]
Thanks, merged as 6d48636929d5002ddce0fd9bca1cf37f2bddddf8

**Pull request closed without merging**
