### PR TITLE
DAT-10919 refactor to use reusable workflows

### PR DESCRIPTION
**Pull request by jnewton03**

### CODE REVIEW

**Review by mcred — APPROVED** [review]

**Review by nvoxland — CHANGES_REQUESTED** [review]
Sent suggested changes via slack

**Comment by kevin-atx** [comment]
Hey @nvoxland - I see that @jnewton03 added the secrets management that would remove the need to have the safe_to_build label. That's excellent. Is there any reason why we shouldn't just merge these changes to make a step forward?

**Comment by nvoxland** [comment]
@kevin-atx Yes, there is the whole list of things I sent in slack that keeps us from being able to merge this in. There has been a little bit of talk there, but nothing changed in this PR since then.

**Comment by fbiville** [comment]
Hello, thanks for the work.
1 question: how can I parameterized Neo4j version for integration tests?
I need to run container-based tests against Neo4j 3.5 to 5.x.
This used to be [here](https://github.com/liquibase/liquibase-neo4j/blob/1add08691dced24a5abdada063abc7aac992a4e1/.github/workflows/pull-request.yml#L26-L35) and is picked up here by this [test utility](https://github.com/liquibase/liquibase-neo4j/blob/1add08691dced24a5abdada063abc7aac992a4e1/src/test/groovy/liquibase/ext/neo4j/DockerNeo4j.groovy#L22-L28).

**Comment by kevin-atx** [comment]
Hey @fbiville - I reached out to our DevOps person who is currently woking on updaing the build process. I asked him to include the Neo4j integration test matrix into his effort.

**Comment by jnewton03** [comment]
HI @fbiville , let me chat with @mcred about how we can integrate your additional matrix requirements.

**Comment by jnewton03** [comment]
hi @fbiville , @mcred and I added extended the reusable workflows to add your integration tests.  On the PR it looks like the tests are passing on ubuntu, but not windows.  Do you want to take a look?

**Comment by jnewton03** [comment]
@fbiville Thanks for the fix splitting unit and integration tests.  It looks like this is now working correctly!

**Review by mcred — APPROVED** [review]

**Pull request merged**
